clasrum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clasrum import views

app_name = "clasrum"

urlpatterns = [    
    path('home', views.home, name='home'),

    path('teacher/list', views.teacher_list, name='teacher_list'),
    path('teacher/create', views.teacher_create, name='teacher_create'),
    path('teacher/update/<int:teacher_ID>', views.teacher_update, name='teacher_update'),
    path('teacher/delete/<int:teacher_ID>', views.teacher_delete, name='teacher_delete'),

    path('student/list', views.student_list, name='student_list'),
    path('student/create', views.student_create, name='student_create'),
    path('student/update/<int:student_ID>', views.student_update, name='student_update'),
    path('student/delete/<int:student_ID>', views.student_delete, name='student_delete'),    

    path('grade/list', views.grade_list, name='grade_list'),
    path('grade/create', views.grade_create, name='grade_create'),
    path('grade/update/<int:grade_ID>', views.grade_update, name='grade_update'),
    path('grade/delete/<int:grade_ID>', views.grade_delete, name='grade_delete'),    

    path('subject/list', views.subject_list, name='subject_list'),
    path('subject/create', views.subject_create, name='subject_create'),
    path('subject/update/<int:subject_ID>', views.subject_update, name='subject_update'),
    path('subject/delete/<int:subject_ID>', views.subject_delete, name='subject_delete'),

    path('test/list', views.test_list, name='test_list'),
    path('test/create', views.test_create, name='test_create'),
    path('test/update/<int:test_ID>', views.test_update, name='test_update'),
    path('test/delete/<int:test_ID>', views.test_delete, name='test_delete'),

    path('testscore/list', views.testscore_list, name='testscore_list'),
    path('testscore/create', views.testscore_create, name='testscore_create'),
    path('testscore/update/<int:testscore_ID>', views.testscore_update, name='testscore_update'),
    path('testscore/delete/<int:testscore_ID>', views.testscore_delete, name='testscore_delete'),

    path('mytestscores/', views.mytestscores, name='mytestscores'),
    path('mytests/', views.mytests, name='mytests'),

    path('guide/list', views.guide_list, name='guide_list'),
    path('guide/create', views.guide_create, name='guide_create'),
    path('guide/update/<int:guide_ID>', views.guide_update, name='guide_update'),
    path('guide/delete/<int:guide_ID>', views.guide_delete, name='guide_delete'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clasrum import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('clasrum/', include('clasrum.urls')),
    path('auth/', include('auth_login.urls')),
    path('contacts/', include('contacts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clasrum/forms.py
from django import forms
from clasrum.models import Teacher, Grade, Student, Subject, Test, TestScore, Guide

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = (
            'Teacher_First_Name',
            'Teacher_Last_Name',
            'Teacher_Rut',
            'Teacher_Date',
            'Teacher_Email',
            'Teacher_Photo'
        )

class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = (
            'Grade_Teacher',
            'Grade_Name',
            'Grade_Code',
            'Grade_Logo'
        )
        
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = (
            'Subject_Grade',
            'Subject_Type',
        )

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'Student_Grade',
            'Student_First_Name',
            'Student_Last_Name',
            'Student_Rut',
            'Student_Date',
            'Student_Email',
            'Student_Photo'
        )

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = (
            'Test_Subject',
            'Test_Name',
            'Test_File'
        )

class TestScoreForm(forms.ModelForm):
    class Meta:
        model = TestScore
        fields = (
            'TestScore_Test',
            'TestScore_Student',
            'TestScore_Score'
        )

class GuideForm(forms.ModelForm):
    class Meta:
        model = Guide
        fields = (
            'Guide_Subject',
            'Guide_Name',
            'Guide_File'
        )

clasrum/views.py
from django.shortcuts import render, redirect
from clasrum.models import Teacher, Student, Grade, Subject, Test, TestScore, Guide
from clasrum.forms import TeacherForm, StudentForm, GradeForm, SubjectForm, TestForm, TestScoreForm, GuideForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.

def home(request):
    template_name = 'home.html'
    data = {}
    data['title'] = 'Home'

    return render(request, template_name, data)





#TEACHER VIEWS
@permission_required('clasrum.add_teacher')
def teacher_create(request):
    data = {}
    template_name = 'teacher_create.html'
    data['title'] = 'Create Teacher'
    data['form'] = TeacherForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Teacher Created.'
                )
        return redirect('clasrum:teacher_list')

    return render(request, template_name, data)


@login_required()
def teacher_list(request):
    template_name = 'teacher_list.html'
    data = {}
    data['title'] = 'Teacher List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        lists = Teacher.objects.filter(Teacher_Last_Name__icontains=data['query'])
    else:
        lists = Teacher.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(lists, 5)
    try:
        data['teachers'] = paginator.page(page)
    except PageNotAnInteger:
        data['teachers'] = paginator.page(1)
    except EmptyPage:
        data['teachers'] = paginator.page(paginator.num_pages)
    
    return render(request, template_name, data)


@permission_required('clasrum.change_teacher')
def teacher_update(request, teacher_ID):
    data = {}
    template_name = 'teacher_update.html'
    data['title'] = 'Update Teacher'
    teacher = Teacher.objects.get(id=teacher_ID)
    if request.method == 'POST':
        data['form'] = TeacherForm(request.POST, files=request.FILES, instance=teacher)
        if data['form'].is_valid():
            teacher.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Teacher Updated.'
                )
            return redirect('clasrum:teacher_list')
    else:
        data['form'] = TeacherForm(instance=teacher)

    return render(request, template_name, data)


@permission_required('clasrum.delete_teacher')
def teacher_delete(request, teacher_ID):
    data = {}
    template_name = 'teacher_delete.html'
    data['title'] = 'Delete Teacher'
    data['teacher'] = Teacher.objects.get(id=teacher_ID)
    if request.method == 'POST':
        data['teacher'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Teacher Deleted.'
                )
        return redirect('clasrum:teacher_list')

    return render(request, template_name, data)





#STUDENT VIEWS
@permission_required('clasrum.add_student')
def student_create(request):
    data = {}
    template_name = 'student_create.html'
    data['title'] = 'Create Student'
    data['form'] = StudentForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Student Created.'
                )
        return redirect('clasrum:student_list')

    return render(request, template_name, data)


@login_required()
def student_list(request):
    template_name = 'student_list.html'
    data = {}
    data['title'] = 'Student List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        data['students'] = Student.objects.filter(Student_Last_Name__icontains=data['query'])
    else:
        data['students'] = Student.objects.all()
    g = Grade.objects.all().order_by('Grade_Name')  
    page = request.GET.get('page', 1)
    paginator = Paginator(g, 5)
    try:
        data['grades'] = paginator.page(page)
    except PageNotAnInteger:
        data['grades'] = paginator.page(1)
    except EmptyPage:
        data['grades'] = paginator.page(paginator.num_pages)

    return render(request, template_name, data)


@permission_required('clasrum.change_student')
def student_update(request, student_ID):
    data = {}
    template_name = 'student_update.html'
    data['title'] = 'Update Student'
    student = Student.objects.get(id=student_ID)
    if request.method == 'POST':
        data['form'] = StudentForm(request.POST, files=request.FILES, instance=student)
        if data['form'].is_valid():
            student.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Student Updated.'
                )
            return redirect('clasrum:student_list')
    else:
        data['form'] = StudentForm(instance=student)

    return render(request, template_name, data)


@permission_required('clasrum.delete_student')
def student_delete(request, student_ID):
    data = {}
    template_name = 'student_delete.html'
    data['title'] = 'Delete Student'
    data['student'] = Student.objects.get(id=student_ID)
    if request.method == 'POST':
        data['student'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Student Deleted.'
                )
        return redirect('clasrum:student_list')

    return render(request, template_name, data)





#GRADE VIEWS
@permission_required('clasrum.add_grade')
def grade_create(request):
    data = {}
    template_name = 'grade_create.html'
    data['title'] = 'Create Grade'
    data['form'] = GradeForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Grade Created.'
                )
        return redirect('clasrum:grade_list')

    return render(request, template_name, data)


@login_required()
def grade_list(request):
    template_name = 'grade_list.html'
    data = {}
    data['title'] = 'Grade List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        lists = Grade.objects.filter(Grade_Name__icontains=data['query'])
    else:
        lists = Grade.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(lists, 5)
    try:
        data['grades'] = paginator.page(page)
    except PageNotAnInteger:
        data['grades'] = paginator.page(1)
    except EmptyPage:
        data['grades'] = paginator.page(paginator.num_pages)
    
    return render(request, template_name, data)


@permission_required('clasrum.change_grade')
def grade_update(request, grade_ID):
    data = {}
    template_name = 'grade_update.html'
    data['title'] = 'Update Grade'
    grade = Grade.objects.get(id=grade_ID)
    if request.method == 'POST':
        data['form'] = GradeForm(request.POST, files=request.FILES, instance=grade)
        if data['form'].is_valid():
            grade.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Grade Updated.'
                )
            return redirect('clasrum:grade_list')
    else:
        data['form'] = GradeForm(instance=grade)

    return render(request, template_name, data)


@permission_required('clasrum.delete_grade')
def grade_delete(request, grade_ID):
    data = {}
    template_name = 'grade_delete.html'
    data['title'] = 'Delete grade'
    data['grade'] = Grade.objects.get(id=grade_ID)
    if request.method == 'POST':
        data['grade'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Grade Deleted.'
                )
        return redirect('clasrum:grade_list')

    return render(request, template_name, data)





#SUBJECT VIEWS
@permission_required('clasrum.add_subject')
def subject_create(request):
    data = {}
    template_name = 'subject_create.html'
    data['title'] = 'Create Subject'
    data['form'] = SubjectForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Subject Created.'
                )
        return redirect('clasrum:subject_list')

    return render(request, template_name, data)

@login_required()
def subject_list(request):
    template_name = 'subject_list.html'
    data = {}
    data['title'] = 'Subject List'
    data['subjects'] = Subject.objects.all()
    data['grades'] = Grade.objects.all().order_by('Grade_Name')  

    return render(request, template_name, data)


@permission_required('clasrum.change_subject')
def subject_update(request, subject_ID):
    data = {}
    template_name = 'subject_update.html'
    data['title'] = 'Update Subject'
    subject = Subject.objects.get(id=subject_ID)
    if request.method == 'POST':
        data['form'] = SubjectForm(request.POST, files=request.FILES, instance=subject)
        if data['form'].is_valid():
            Subject.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Subject Updated.'
                )
            return redirect('clasrum:subject_list')
    else:
        data['form'] = SubjectForm(instance=subject)

    return render(request, template_name, data)


@permission_required('clasrum.delete_subject')
def subject_delete(request, subject_ID):
    data = {}
    template_name = 'subject_delete.html'
    data['title'] = 'Delete Subject'

clasrum/templates/grade_list.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Grade List
{% endblock %}

{% block extra_css %}
    <style>
        .color_update{
            color: goldenrod;
            font-size: 22px;
        }
        .color_delete{
            color: red;
            font-size: 22px;
        }
    </style>
{% endblock %}

{% block content_head %}
<!--Title Block-->
<div class="row mt-2">
    <div class="col-md-6 col-lg-6">
        <h1>{{ title }}</h1>
    </div>
    <div class="col-md-4 col-lg-4">
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'clasrum:grade_list' %}">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    {% if user.is_superuser %}
    <div class="col-md-2 col-lg-2">
        <a href="{% url 'clasrum:grade_create' %}" class="btn btn-success btn-block mt-2">
            <i class="fas fa-user-plus"></i> | Create Grade
        </a>
    </div>
    {% endif %}
</div>
<!--End Title Block-->
{% endblock %}

{% block content_body %}
    <!--Table Block-->
    <div class="row">
        <div class="col">
            {% if grades %}
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>Logo</th>
                            <th>Grade Name</th>
                            <th>Teacher</th>
                            <th>Code</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for x in grades %}
                            <tr>
                                <td><img src="/media/{{x.Grade_Logo}} " alt="Grade Logo" id="logo" width="75" height="60"></td>
                                <td>{{x.Grade_Name}}</td>
                                <td>{{x.Grade_Teacher}}</td>
                                <td>{{x.Grade_Code}}</td>
                                <td>
                                    {% if user.is_superuser or user.teacher.grade.Grade_Name == x.Grade_Name %}
                                    <a href="{% url 'clasrum:grade_update' x.id %}">
                                        <i class="fas fa-edit color_update"></i>
                                    </a>
                                    {% endif %} | 
                                    {% if user.is_superuser %}
                                    <a href="{% url 'clasrum:grade_delete' x.id %}">
                                        <i class="fas fa-trash-alt color_delete"></i>
                                    </a>{% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            <hr>

            <nav aria-label="Page navigation example">
                {% if grades.has_other_pages %}
                    <ul class="pagination">

                        {% if grades.has_previous %}
                            <li class="page-item"><a href="?q={{query}}&page={{ grades.previous_page_number }}" class="page-link">&laquo;</a></li>
                        {% else %}
                            <li class="page-item" class="disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}

                        {% for i in grades.paginator.page_range %}
                            {% if grades.number == i %}
                                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?q={{query}}&page={{ i }}">{{ i }}</a></li>
                            {% endif %}

                        {% endfor %}
                        {% if grade.has_next %}
                            <li class="page-item"><a href="?q={{query}}&page={{ grades.next_page_number }}" class="page-link">&raquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </nav>
            {% else %}
                <p>No results</p>
            {% endif %}
        </div>
    </div>
    <!--End Table Block-->
{% endblock %}

clasrum/templates/guide_create.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Create Guide
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success btn-lg">
                Save
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

clasrum/templates/guide_list.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Guide List
{% endblock %}

{% block extra_css %}
    <style>
        .color_update{
            color: goldenrod;
            font-size: 22px;
        }
        .color_delete{
            color: red;
            font-size: 22px;
        }
    </style>
{% endblock %}

{% block search %}
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'clasrum:guide_list' %}">
                <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
{% endblock %}

{% block content_head %}
<!--Title Block-->
<div class="row mt-2">
    <div class="col-md-6 col-lg-6">
        <h1>{{ title }}</h1>
    </div>
    {% if user.is_superuser or user.teacher %}
    <div class="col-md-2 col-lg-2">
        <a href="{% url 'clasrum:guide_create' %}" class="btn btn-success btn-block mt-2">
            <i class="fas fa-user-plus"></i> | Create guide
        </a>
    </div>
    {% endif %}
</div>
<!--End Title Block-->
{% endblock %}

{% block content_body %}
    <!--Table Block-->
    <div class="row">
        <div class="col">
            {% if guides %}
                {% for x in grades %}
                {% if user.is_superuser or user.teacher.grade.Grade_Name == x.Grade_Name or user.student.Student_Grade.Grade_Name == x.Grade_Name %}
                <h1>{{x.Grade_Name}}</h1>
                    {% for y in subjects %}
                        {% if x == y.Subject_Grade %}
                            <h2>{{y.Subject_Type}}</h2>
                            <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Name</th>
                                        <th>File</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for z in guides %}
                                    {% if z.Guide_Subject.id == y.id %}
                                        <tr>
                                            <td>{{z.Guide_Name}}</td>
                                            <td><a href="/media/{{z.Guide_File}}" download={{z.Guide_File}}>{{z.Guide_File}}</a></td>
                                            <td>
                                                {% if user.is_superuser or user.teacher.grade.Grade_Name == x.Grade_Name %}
                                                <a href="{% url 'clasrum:guide_update' z.id %}">
                                                    <i class="fas fa-edit color_update"></i>
                                                </a>
                                                {% endif %} | 
                                                {% if user.is_superuser %}
                                                <a href="{% url 'clasrum:guide_delete' z.id %}">
                                                    <i class="fas fa-trash-alt color_delete"></i>
                                                </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% endfor %}
            
            <hr>

            <nav aria-label="Page navigation example">
                {% if guides.has_other_pages %}
                    <ul class="pagination">

                        {% if grades.has_previous %}
                            <li class="page-item"><a href="?q={{query}}&page={{ grades.previous_page_number }}" class="page-link">&laquo;</a></li>
                        {% else %}
                            <li class="page-item" class="disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}

                        {% for i in grades.paginator.page_range %}
                            {% if grades.number == i %}
                                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?q={{query}}&page={{ i }}">{{ i }}</a></li>
                            {% endif %}

                        {% endfor %}
                        {% if grades.has_next %}
                            <li class="page-item"><a href="?q={{query}}&page={{ grades.next_page_number }}" class="page-link">&raquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </nav>
            {% else %}
                <p>No Results</p>
            {% endif %}
        </div>
    </div>
    <!--End Table Block-->
{% endblock %}

clasrum/templates/home.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
    {{title}}
{% endblock %}

{% block content_body %}
{% endblock %}

clasrum/templates/test_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Delete Subject
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h2>¿Are you sure to delete <strong> {{test.Test_File}}</strong> ? </h2>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete"> | 
        <a href="{% url 'clasrum:test_list' %}" class="btn btn-light">Cancel</a>
    </form>
{% endblock %}

clasrum/templates/test_list.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Test List
{% endblock %}

{% block extra_css %}
    <style>
        .color_update{
            color: goldenrod;
            font-size: 22px;
        }
        .color_delete{
            color: red;
            font-size: 22px;
        }
    </style>
{% endblock %}

{% block content_head %}
<!--Title Block-->
<div class="row mt-2">
    <div class="col-md-6 col-lg-6">
        <h1>{{ title }}</h1>
    </div>
    <div class="col-md-4 col-lg-4">
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'clasrum:test_list' %}">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    {% if user.teacher or user.is_superuser %}
    <div class="col-md-2 col-lg-2">
        <a href="{% url 'clasrum:test_create' %}" class="btn btn-success btn-block mt-2">
            <i class="fas fa-user-plus"></i> | Create Test
        </a>
    </div>
    {% endif %}
</div>
<!--End Title Block-->
{% endblock %}

{% block content_body %}
    <!--Table Block-->
    <div class="row">
        <div class="col">
            {% if tests %}
                {% for x in grades %}
                {% if user.is_superuser or user.teacher.grade.Grade_Name == x.Grade_Name or user.student.Student_Grade.Grade_Name == x.Grade_Name %}
                <h1>{{x.Grade_Name}}</h1>
                    {% for y in subjects %}
                        {% if x == y.Subject_Grade %}
                        <h2>{{y.Subject_Type}}</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Name</th>
                                        <th>File</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for z in tests %}
                                    {% if z.Test_Subject.id == y.id %}
                                        <tr>
                                            <td>{{z.Test_Name}}</td>
                                            <td><a href="/media/{{z.Test_File}}" download={{z.Test_File}}>{{z.Test_File}}</a></td>
                                            <td>
                                                {% if user.is_superuser or user.teacher.grade.Grade_Name == x.Grade_Name %}
                                                <a href="{% url 'clasrum:test_update' z.id %}">
                                                    <i class="fas fa-edit color_update"></i>
                                                </a>
                                                {% endif %} | 
                                                {% if user.is_superuser %}
                                                <a href="{% url 'clasrum:test_delete' z.id %}">
                                                    <i class="fas fa-trash-alt color_delete"></i>
                                                </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% endfor %}
            
            <hr>

            {% else %}
                <p>No Results</p>
            {% endif %}
        </div>
    </div>
    <!--End Table Block-->
{% endblock %}

clasrum/templates/testscore_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Delete Test Score
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h2>¿Are you sure to delete <strong> {{testscore.TestScore_Score}}  {{testscore.TestScore_Test}}  {{testscore.TestScore_Student}}</strong> ? </h2>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete"> | 
        <a href="{% url 'clasrum:testscore_list' %}" class="btn btn-light">Cancel</a>
    </form>
{% endblock %}