auth_login/urls.py
from django.urls import path
from auth_login import views

app_name = 'auth'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('change_pw', views.change_pw, name='change_pw'),
    path('edit_user', views.edit_user, name='edit_user'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clasrum import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('clasrum/', include('clasrum.urls')),
    path('auth/', include('auth_login.urls')),
    path('contacts/', include('contacts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth_login/models.py
from django.db import models

auth_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

class UserClasrumForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=100)

class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name'
            )

auth_login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from auth_login.forms import UserClasrumForm, EditUserForm

def login(request):
    data = {}
    template_name = 'login.html'
    data['title'] = 'Clasrum - Login'

    auth.logout(request)

    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(
            username=username,
            password=password
        )
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                return redirect('clasrum:home')

            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'User or Password Wrong.'
                )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'User or Password Wrong.'
            )

    return render(request, template_name, data)

def logout(request):
    auth.logout(request)
    return redirect('clasrum:home')

def register(request):
    data = {}
    template_name = 'register.html'
    data['title'] = 'Clasrum - Register'
    data['form'] = UserClasrumForm(request.POST or None)

    if request.method == 'POST':
        if data['form'].is_valid():
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    password=request.POST['password'],
                )

                user.save()

                messages.add_message(
                  request,
                  messages.SUCCESS,
                  'User Created.'
                )

            except IntegrityError as ie:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Error while creating user ERROR: {error}.' .format(error=str(ie))
                )

            except ValidationError as ve:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Problems with form validation: {error}.' .format(error=str(ie))
                )

            return redirect('auth:login')

        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Error while creating user.'
            )

    return render(request, template_name, data)

@login_required()
def edit_user(request):
    data = {}
    template_name = 'edit_user.html'
    data['title'] = 'Update User'
    if request.method == 'POST':
        data['form'] = EditUserForm(request.POST, instance=request.user)
        if data['form'].is_valid():
            try:
                data['form'].save()
                messages.add_message(
                            request,
                            messages.INFO,
                            'User Updated.'
                        )
                return redirect('clasrum:home')

            except IntegrityError as ie:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Error while editing user ERROR: {error}.' .format(error=str(ie))
                )

            except ValidationError as ve:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Problems with form validation: {error}.' .format(error=str(ie))
                )

        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Error while editing user.'
                )
    else:
        data['form'] = EditUserForm(instance=request.user)

    return render(request, template_name, data)

@login_required()
def change_pw(request):
    data = {}
    template_name = 'change_pw.html'
    data['title'] = 'Update User'
    if request.method == 'POST':
        data['form'] = PasswordChangeForm(data=request.POST, user=request.user)
        if data['form'].is_valid():
            try:
                data['form'].save()
                messages.add_message(
                            request,
                            messages.INFO,
                            'User Updated.'
                        )
                return redirect('clasrum:home')

            except IntegrityError as ie:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Error while changing password ERROR: {error}.' .format(error=str(ie))
                )

            except ValidationError as ve:
                messages.add_message(
                  request,
                  messages.ERROR,
                  'Problems with form validation: {error}.' .format(error=str(ie))
                )

        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Error while changing password.'
                )
    else:
        data['form'] = PasswordChangeForm(user=request.user)

    return render(request, template_name, data)

auth_login/templates/change_pw.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Update User
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success btn-lg">
                <i class="fas fa-key"></i>  Save
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

auth_login/templates/edit_user.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block title %}
    Update User
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success btn-lg">
                Save
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

auth_login/templates/login.html
{% load static %}
<!doctype html>
<html lang="es-cl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/floating-labels/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'images/logo_clasrum.png' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
  </head>
  <body>
    <!--Title Block-->
    
    <!--End Title Block-->
    <form class="form-signin" method="POST">{% csrf_token %}
      <div class="text-center mb-4">
        <img class="mb-4" src="{% static 'images/logo_clasrum.png' %}" alt="" width="250" height="250">
        <hr>
        <h1 class="h3 mb-3 font-weight-normal"> Login </h1>

      </div>

      <div class="form-label-group">
        <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="username">Username</label>
      </div>

      <div class="form-label-group">
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
        <label for="password">Password</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      <hr>
      <a href="{% url 'auth:register' %}" class="btn btn-success btn-block mt-2"><i class="fas fa-user-plus"></i> Create</a>
      <hr>
      <p class="mt-5 mb-3 text-muted text-center">&copy; 2020</p>
    </form>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

auth_login/templates/register.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}
    Create User
{% endblock %}

{% block content_head %}
    <!--Title Block-->
    <div class="row mt-2">
        <div class="col-md-8 col-lg-10">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <!--End Title Block-->
{% endblock %}

{% block content_body %}
    {% bootstrap_messages %}
    <form class="" method="post" >
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-success btn-lg">
            Save
        </button>
        {% endbuttons %}
    </form>
{% endblock %}