auth_login/urls.py
from django.urls import path
from auth_login import views

app_name = 'auth'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('change_pw', views.change_pw, name='change_pw'),
    path('edit_user', views.edit_user, name='edit_user'),
]

clasrum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clasrum import views

app_name = "clasrum"

urlpatterns = [    
    path('home', views.home, name='home'),

    path('teacher/list', views.teacher_list, name='teacher_list'),
    path('teacher/create', views.teacher_create, name='teacher_create'),
    path('teacher/update/<int:teacher_ID>', views.teacher_update, name='teacher_update'),
    path('teacher/delete/<int:teacher_ID>', views.teacher_delete, name='teacher_delete'),

    path('student/list', views.student_list, name='student_list'),
    path('student/create', views.student_create, name='student_create'),
    path('student/update/<int:student_ID>', views.student_update, name='student_update'),
    path('student/delete/<int:student_ID>', views.student_delete, name='student_delete'),    

    path('grade/list', views.grade_list, name='grade_list'),
    path('grade/create', views.grade_create, name='grade_create'),
    path('grade/update/<int:grade_ID>', views.grade_update, name='grade_update'),
    path('grade/delete/<int:grade_ID>', views.grade_delete, name='grade_delete'),    

    path('subject/list', views.subject_list, name='subject_list'),
    path('subject/create', views.subject_create, name='subject_create'),
    path('subject/update/<int:subject_ID>', views.subject_update, name='subject_update'),
    path('subject/delete/<int:subject_ID>', views.subject_delete, name='subject_delete'),

    path('test/list', views.test_list, name='test_list'),
    path('test/create', views.test_create, name='test_create'),
    path('test/update/<int:test_ID>', views.test_update, name='test_update'),
    path('test/delete/<int:test_ID>', views.test_delete, name='test_delete'),

    path('testscore/list', views.testscore_list, name='testscore_list'),
    path('testscore/create', views.testscore_create, name='testscore_create'),
    path('testscore/update/<int:testscore_ID>', views.testscore_update, name='testscore_update'),
    path('testscore/delete/<int:testscore_ID>', views.testscore_delete, name='testscore_delete'),

    path('mytestscores/', views.mytestscores, name='mytestscores'),
    path('mytests/', views.mytests, name='mytests'),

    path('guide/list', views.guide_list, name='guide_list'),
    path('guide/create', views.guide_create, name='guide_create'),
    path('guide/update/<int:guide_ID>', views.guide_update, name='guide_update'),
    path('guide/delete/<int:guide_ID>', views.guide_delete, name='guide_delete'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contacts import views

app_name = "contacts"

urlpatterns = [
    path('send_email/', views.send_email, name='send_email'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clasrum import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('clasrum/', include('clasrum.urls')),
    path('auth/', include('auth_login.urls')),
    path('contacts/', include('contacts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clasrum/forms.py
from django import forms
from clasrum.models import Teacher, Grade, Student, Subject, Test, TestScore, Guide

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = (
            'Teacher_First_Name',
            'Teacher_Last_Name',
            'Teacher_Rut',
            'Teacher_Date',
            'Teacher_Email',
            'Teacher_Photo'
        )

class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = (
            'Grade_Teacher',
            'Grade_Name',
            'Grade_Code',
            'Grade_Logo'
        )
        
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = (
            'Subject_Grade',
            'Subject_Type',
        )

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'Student_Grade',
            'Student_First_Name',
            'Student_Last_Name',
            'Student_Rut',
            'Student_Date',
            'Student_Email',
            'Student_Photo'
        )

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = (
            'Test_Subject',
            'Test_Name',
            'Test_File'
        )

class TestScoreForm(forms.ModelForm):
    class Meta:
        model = TestScore
        fields = (
            'TestScore_Test',
            'TestScore_Student',
            'TestScore_Score'
        )

class GuideForm(forms.ModelForm):
    class Meta:
        model = Guide
        fields = (
            'Guide_Subject',
            'Guide_Name',
            'Guide_File'
        )

clasrum/views.py
from django.shortcuts import render, redirect
from clasrum.models import Teacher, Student, Grade, Subject, Test, TestScore, Guide
from clasrum.forms import TeacherForm, StudentForm, GradeForm, SubjectForm, TestForm, TestScoreForm, GuideForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.

def home(request):
    template_name = 'home.html'
    data = {}
    data['title'] = 'Home'

    return render(request, template_name, data)





#TEACHER VIEWS
@permission_required('clasrum.add_teacher')
def teacher_create(request):
    data = {}
    template_name = 'teacher_create.html'
    data['title'] = 'Create Teacher'
    data['form'] = TeacherForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Teacher Created.'
                )
        return redirect('clasrum:teacher_list')

    return render(request, template_name, data)


@login_required()
def teacher_list(request):
    template_name = 'teacher_list.html'
    data = {}
    data['title'] = 'Teacher List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        lists = Teacher.objects.filter(Teacher_Last_Name__icontains=data['query'])
    else:
        lists = Teacher.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(lists, 5)
    try:
        data['teachers'] = paginator.page(page)
    except PageNotAnInteger:
        data['teachers'] = paginator.page(1)
    except EmptyPage:
        data['teachers'] = paginator.page(paginator.num_pages)
    
    return render(request, template_name, data)


@permission_required('clasrum.change_teacher')
def teacher_update(request, teacher_ID):
    data = {}
    template_name = 'teacher_update.html'
    data['title'] = 'Update Teacher'
    teacher = Teacher.objects.get(id=teacher_ID)
    if request.method == 'POST':
        data['form'] = TeacherForm(request.POST, files=request.FILES, instance=teacher)
        if data['form'].is_valid():
            teacher.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Teacher Updated.'
                )
            return redirect('clasrum:teacher_list')
    else:
        data['form'] = TeacherForm(instance=teacher)

    return render(request, template_name, data)


@permission_required('clasrum.delete_teacher')
def teacher_delete(request, teacher_ID):
    data = {}
    template_name = 'teacher_delete.html'
    data['title'] = 'Delete Teacher'
    data['teacher'] = Teacher.objects.get(id=teacher_ID)
    if request.method == 'POST':
        data['teacher'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Teacher Deleted.'
                )
        return redirect('clasrum:teacher_list')

    return render(request, template_name, data)





#STUDENT VIEWS
@permission_required('clasrum.add_student')
def student_create(request):
    data = {}
    template_name = 'student_create.html'
    data['title'] = 'Create Student'
    data['form'] = StudentForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Student Created.'
                )
        return redirect('clasrum:student_list')

    return render(request, template_name, data)


@login_required()
def student_list(request):
    template_name = 'student_list.html'
    data = {}
    data['title'] = 'Student List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        data['students'] = Student.objects.filter(Student_Last_Name__icontains=data['query'])
    else:
        data['students'] = Student.objects.all()
    g = Grade.objects.all().order_by('Grade_Name')  
    page = request.GET.get('page', 1)
    paginator = Paginator(g, 5)
    try:
        data['grades'] = paginator.page(page)
    except PageNotAnInteger:
        data['grades'] = paginator.page(1)
    except EmptyPage:
        data['grades'] = paginator.page(paginator.num_pages)

    return render(request, template_name, data)


@permission_required('clasrum.change_student')
def student_update(request, student_ID):
    data = {}
    template_name = 'student_update.html'
    data['title'] = 'Update Student'
    student = Student.objects.get(id=student_ID)
    if request.method == 'POST':
        data['form'] = StudentForm(request.POST, files=request.FILES, instance=student)
        if data['form'].is_valid():
            student.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Student Updated.'
                )
            return redirect('clasrum:student_list')
    else:
        data['form'] = StudentForm(instance=student)

    return render(request, template_name, data)


@permission_required('clasrum.delete_student')
def student_delete(request, student_ID):
    data = {}
    template_name = 'student_delete.html'
    data['title'] = 'Delete Student'
    data['student'] = Student.objects.get(id=student_ID)
    if request.method == 'POST':
        data['student'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Student Deleted.'
                )
        return redirect('clasrum:student_list')

    return render(request, template_name, data)





#GRADE VIEWS
@permission_required('clasrum.add_grade')
def grade_create(request):
    data = {}
    template_name = 'grade_create.html'
    data['title'] = 'Create Grade'
    data['form'] = GradeForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Grade Created.'
                )
        return redirect('clasrum:grade_list')

    return render(request, template_name, data)


@login_required()
def grade_list(request):
    template_name = 'grade_list.html'
    data = {}
    data['title'] = 'Grade List'
    data['query'] = ''
    if 'q' in request.GET:
        data['query'] = request.GET.get('q')
        lists = Grade.objects.filter(Grade_Name__icontains=data['query'])
    else:
        lists = Grade.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(lists, 5)
    try:
        data['grades'] = paginator.page(page)
    except PageNotAnInteger:
        data['grades'] = paginator.page(1)
    except EmptyPage:
        data['grades'] = paginator.page(paginator.num_pages)
    
    return render(request, template_name, data)


@permission_required('clasrum.change_grade')
def grade_update(request, grade_ID):
    data = {}
    template_name = 'grade_update.html'
    data['title'] = 'Update Grade'
    grade = Grade.objects.get(id=grade_ID)
    if request.method == 'POST':
        data['form'] = GradeForm(request.POST, files=request.FILES, instance=grade)
        if data['form'].is_valid():
            grade.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Grade Updated.'
                )
            return redirect('clasrum:grade_list')
    else:
        data['form'] = GradeForm(instance=grade)

    return render(request, template_name, data)


@permission_required('clasrum.delete_grade')
def grade_delete(request, grade_ID):
    data = {}
    template_name = 'grade_delete.html'
    data['title'] = 'Delete grade'
    data['grade'] = Grade.objects.get(id=grade_ID)
    if request.method == 'POST':
        data['grade'].delete()
        messages.add_message(
                    request,
                    messages.ERROR,
                    'Grade Deleted.'
                )
        return redirect('clasrum:grade_list')

    return render(request, template_name, data)





#SUBJECT VIEWS
@permission_required('clasrum.add_subject')
def subject_create(request):
    data = {}
    template_name = 'subject_create.html'
    data['title'] = 'Create Subject'
    data['form'] = SubjectForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Subject Created.'
                )
        return redirect('clasrum:subject_list')

    return render(request, template_name, data)

@login_required()
def subject_list(request):
    template_name = 'subject_list.html'
    data = {}
    data['title'] = 'Subject List'
    data['subjects'] = Subject.objects.all()
    data['grades'] = Grade.objects.all().order_by('Grade_Name')  

    return render(request, template_name, data)


@permission_required('clasrum.change_subject')
def subject_update(request, subject_ID):
    data = {}
    template_name = 'subject_update.html'
    data['title'] = 'Update Subject'
    subject = Subject.objects.get(id=subject_ID)
    if request.method == 'POST':
        data['form'] = SubjectForm(request.POST, files=request.FILES, instance=subject)
        if data['form'].is_valid():
            Subject.save()
            messages.add_message(
                    request,
                    messages.INFO,
                    'Subject Updated.'
                )
            return redirect('clasrum:subject_list')
    else:
        data['form'] = SubjectForm(instance=subject)

    return render(request, template_name, data)


@permission_required('clasrum.delete_subject')
def subject_delete(request, subject_ID):
    data = {}
    template_name = 'subject_delete.html'
    data['title'] = 'Delete Subject'

clasrum/templates/_partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-xl navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'clasrum:home' %}">
        <img src="{% static 'images/logo_clasrum.png' %}" alt="Logo clasrum" id="logo" width="75" height="75">
        <h1 class="tm-site-title mb-0">CLASRUM</h1>
    </a>
    <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">

            {% if user.student %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Tests
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:mytestscores' %}">Scores</a>
                    <a class="dropdown-item" href="{% url 'clasrum:mytests' %}">Download</a>
                </div>
            </li>
            {% endif %}

            {% if user.student %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Guide
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:guide_list' %}">Download</a>
                    {% if user.is_superuser or user.teacher %}
                    <a class="dropdown-item" href="{% url 'clasrum:guide_create' %}">Create</a>
                    {% endif %}
                </div>
            </li>
            {% endif %}
            
            {% if user.is_active %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Teacher
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:teacher_list' %}">List</a>
                    {% if user.is_superuser or user.teacher %}
                    <a class="dropdown-item" href="{% url 'clasrum:teacher_create' %}">Create</a>
                    {% endif %}
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Student
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:student_list' %}">List</a>
                    {% if user.is_superuser or user.teacher %}
                    <a class="dropdown-item" href="{% url 'clasrum:student_create' %}">Create</a>
                    {% endif %}
                </div>
            </li>

            {% endif %}

            {% if user.is_superuser or user.teacher %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Grade
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:grade_list' %}">List</a>
                    {% if user.is_superuser or user.teacher %}
                    <a class="dropdown-item" href="{% url 'clasrum:grade_create' %}">Create</a>
                    {% endif %}
                </div>
            </li>
            {% endif %}

            {% if user.is_superuser or user.teacher %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Subject
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:subject_list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'clasrum:subject_create' %}">Create</a>
                </div>
            </li>
            {% endif %}

            {% if user.is_superuser or user.teacher %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Test
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:test_list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'clasrum:test_create' %}">Create</a>
                </div>
            </li>
            {% endif %}

            {% if user.is_superuser or user.teacher %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Test Scores
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:testscore_list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'clasrum:testscore_create' %}">Create</a>
                </div>
            </li>
            {% endif %}

            {% if user.is_superuser or user.teacher %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Guide
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'clasrum:guide_list' %}">List</a>
                    {% if user.is_superuser or user.teacher %}
                    <a class="dropdown-item" href="{% url 'clasrum:guide_create' %}">Create</a>
                    {% endif %}
                </div>
            </li>
            {% endif %}

            {% if user.is_active %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Settings
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'auth:edit_user' %}">Edit Profile</a>
                    <a class="dropdown-item" href="{% url 'auth:change_pw' %}">Change Password</a>
                    <a class="dropdown-item" href="{% url 'contacts:send_email' %}">Contact</a>
                </div>
            </li>
            {% endif %}

        </ul>

        <ul class="navbar-nav">
            {% if user.is_active %}
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'auth:logout' %}">
                    <i class="far fa-user mr-2 tm-logout-icon"></i>
                    <span>Logout</span>
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'auth:login' %}">
                    <i class="far fa-user mr-2 tm-logout-icon"></i>
                    <span>Login</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>